[MODULE - 3] & [MODULE 4] completed tasks
js-tasks-ru/vue-20211004_artem-menshakov pull request #5
Opened 2021-10-23 17:21 UTC by hankypanky666

2021-10-23 17:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-23 17:24 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-10-27 18:23 UTC, ShGKme requested changes
Требуется маленькая правка с классами в `01-UiFormGroup1` и исправление серьёзной проблемы `02-TheToaster`

2021-10-27 18:23 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  },
Класс `form-group` должен быть у элемента всегда. А класс `form-group_inline` как [модификатор](https://ru.bem.info/methodology/key-concepts/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80) - в зависимости от входного параметра.

Но не вместо основного класса `form-group`, а вместе с ним.

2021-10-27 18:23 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    </template>
`template` здесь лишний. И цикл, и ключ можно установить сразу на элемент.

2021-10-27 18:23 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
За вывод тоста в вашем решении отвечает компонент `TheToasterItem`, в том числе тост разного типа и их стили в зависимости от параметра `type`. Но иконку для него вычисляет почему-то `TheToaster`, а не компонент самостоятельно. Это мешает использованию компонента `TheToasterItem` независимо от `TheToaster`, требуя всегда определять его иконку. Лучше эту часть также перенести в компонент `TheToasterItem`

2021-10-27 18:23 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +  },
`$options` - это объект с опциями, описанием компонента. Это тот самый объект, на основе которого Vue создаёт экземпляры компонента. Но это объект - один на все экземпляры. `$options` можно использовать для сохранения констант и других статических свойств компонента, но ни в коем случае нельзя использовать в качестве состояния компонента (даже не реактивного). Этот объект **один общий** на все экземпляры компонента. 

`timeoutId` можно сохранить либо в данных компонента (не страшно, что это число реактивное), либо прямо в свойства экземпляра компонента (`this.timeoutId` и без объявления в `data`). Второй вариант может показаться не очень красивым, но JS позволяет нам сохранять любые свойства у объекта. На мой взгляд, тут лучше первый вариант. Реактивное число - не страшно.

2021-10-27 18:23 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +  },
Удалять таймер - правильно. Иначе при уничтожении всего тостера (вдруг) все таймеры останутся в памяти.

2021-10-27 18:23 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
👍

2021-10-28 08:56 UTC, hankypanky666 commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  },
а, понял)

2021-10-28 08:57 UTC, hankypanky666 commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
идея понятна

2021-10-28 08:58 UTC, hankypanky666 commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +  },
я специально его оставил чтобы вы обратили внимание, тк да, заметил, что он общий для всех) спасибо)

2021-10-28 09:12 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-10-28 09:34 UTC, ShGKme approved these changes
Принято 👍

2021-10-28 09:35 UTC, merged